### ISSUE TITLE
Cosmetic Changes To Group Panel

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoDesktop#153]
Hello,

As you can see in the attached image in the area labeled 1, when you have a group with multiple entries, the boxes are not the same size and are based on the image being used for the entry. Can this be changed so that each box is the same size? 

In regards to the arrow pointing at the scroll bar, its pretty useless. Nothing on my screen is being cutoff and it scrolls over only a very little. 

Also I just noticed the image used for the series list on the right-side has this problem as well. 

![jmm-series info](https://cloud.githubusercontent.com/assets/9443295/8302914/ee361612-194e-11e5-89e6-c8e7ad3b47bc.png)

**Comment by jmediamanager** [comment]
This is a bit difficult.
AniDB does not enforce the scale images, so to keep images looking correct I have to keep the height the same and adjust the width.

Also the text is variable length.

Using TvDB images will fix some of these issues since they have consistency.

I will look at the scroll bar though/

**Comment by ElementalCrisis** [comment]
Hello,

Thanks for the suggestion, I'll see how TvDB images look.

**Comment by ElementalCrisis** [comment]
I forgot I had fixed this.

![image](https://user-images.githubusercontent.com/9443295/28246407-01088f32-69ce-11e7-99ec-928d4f15e340.png)
